version: '3.9'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner  # Use 'runner-system' to leverage system node packages
    container_name: nextjs-app
    ports:
      - "4020:3000"
    restart: always
    environment:
      - NODE_ENV=production
      - FILES_BASE_URL=https://files.avan.mx:8080
      - FILES_BASIC_USER=avan#@905
      - FILES_BASIC_PASS=3v3n@509
      - FILES_ACCESS_KEY=3v3n@509_2025
      - FILES_TIMEOUT_MS=10000
    networks:
      - avan-net

networks:
  avan-net:
    external: true
